Repository jdomingu98/ft_transcendence_frontend, pull requests merged in 2024-11, with the labels that each got.

#36 Fix(landing-auth-modal): validation errors
  src/components/app/landing/landing-auth-modal/register-form.js
Labels: bug

#35 Conexion ResetPassword con backend
  src/pages/error-page/error-page.js
  src/pages/reset-password/ResetPassword.css
  src/pages/reset-password/ResetPassword.js
Labels: enhancement

#38 feat(settings): implement settings section
  lib/WebComponent/components/Snackbar.js
  lib/WebComponent/modules/translator/Translator.js
  lib/services/AuthService.js
  lib/services/FetchService.js
  lib/services/UserService.js
  src/components/app/landing/landing-auth-modal/login-form.js
  src/components/app/landing/landing-auth-modal/register-form.js
  src/components/app/profile/profile-header/profile-header.css
  src/components/app/profile/profile-header/profile-header.js
  src/components/app/settings/index.js
  src/components/app/settings/settings-about.js
  src/components/app/settings/settings-change-password.js
  src/components/app/settings/settings-common-styles.css
  src/components/app/settings/settings-delete-account.js
  src/components/app/settings/settings-two-factor-auth.js
  src/components/app/settings/settings-user-management.js
  src/components/common/h2-text.js
  src/components/common/language-selector.js
  src/components/common/primary-button.js
  src/components/common/secondary-button.js
  src/components/common/sub-header-text.js
  src/const.js
  src/i18n/en.json
  src/i18n/es.json
  src/i18n/fr.json
  src/i18n/zh.json
  src/pages/error-page/error-page.js
  src/pages/index.js
  src/pages/ranking/RankingPage.js
  src/pages/reset-password/ResetPassword.css
  src/pages/reset-password/ResetPassword.js
  src/pages/search-results/SearchResults.js
  src/pages/settings/SettingsPage.css
  src/pages/settings/SettingsPage.js
  src/pages/sidebar/MainSidebar.css
  src/pages/sidebar/MainSidebar.js
  src/resources/default-banner.webp
Labels: enhancement

#37 fix(oauth): add otp modal to correctly generate tokens
  src/components/app/landing/landing-auth-modal/login-form.js
  src/components/app/landing/landing-auth-modal/register-form.js
  src/i18n/en.json
  src/i18n/es.json
  src/i18n/fr.json
  src/i18n/zh.json
  src/pages/error-page/ErrorPage.js
  src/pages/index.js
  src/pages/oauth-redirect/OAuthRedirect.js
  src/pages/settings/SettingsPage.js
Labels: bug

#34 feat: create pong game
  .gitignore
  lib/WebComponent/WebComponent.js
  lib/services/GameService.js
  src/i18n/en.json
  src/i18n/es.json
  src/i18n/fr.json
  src/i18n/zh.json
  src/pages/index.js
  src/pages/pong-game/Ball.js
  src/pages/pong-game/GamePage.css
  src/pages/pong-game/GamePage.js
  src/pages/pong-game/Paddle.js
  src/pages/pong-game/PongUtils.js
Labels: enhancement

#40 refactor(match history): generates new layout with local statistics
  public/i18n/en.json
  public/i18n/es.json
  public/i18n/fr.json
  public/i18n/zh.json
  src/components/app/profile/profile-friendship.js
  src/components/app/profile/profile-history/profile-history.css
  src/components/app/profile/profile-history/profile-history.js
  src/const.js
  src/pages/sidebar/MainSidebar.css
Labels: refactor

#41 feat(friendshipPage): add connection to backend
  lib/services/FriendService.js
  public/i18n/en.json
  public/i18n/es.json
  public/i18n/fr.json
  public/i18n/zh.json
  src/pages/friendship/FriendshipPage.css
  src/pages/friendship/FriendshipPage.js
Labels: enhancement
